"""
Import Babelfish Compass DAT file into SQLite database

This script reads the pg_import.dat file generated by Babelfish Compass
and imports it into an SQLite database.

Usage:
    python 03_Import_DAT_to_SQLite.py <report_name>

Arguments:
    report_name - Name of the report (must match Step 1 and Step 2 report name)

Configuration:
    - Settings are loaded from Config/config.json
    - The database name will be: {report_name}.db

Date: 2026-03-19
"""

import sqlite3
import csv
import sys
import re
import logging
import traceback
from pathlib import Path
from typing import Optional
from config_loader import ConfigLoader

# ============================================================================
# CONFIGURATION
# ============================================================================

# Load configuration using ConfigLoader
config_loader = ConfigLoader()

# Get configuration values
SQLITE_DIR = config_loader.get_sqlite_dir()
DEFAULT_REPORT_NAME = config_loader.get_default_report_name()
DAT_FILE_PATTERN = config_loader.get_dat_file_pattern()
REPORT_LOCATION_PATTERN = config_loader.get_report_location_pattern()

# Validate and get table name
def validate_table_name(name: str) -> str:
    """
    Validate SQL table name to prevent SQL injection.

    Args:
        name: The table name to validate

    Returns:
        str: The validated table name

    Raises:
        ValueError: If the table name is invalid
    """
    # SQL identifiers should start with letter or underscore,
    # followed by letters, numbers, or underscores
    if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', name):
        raise ValueError(
            f"Invalid table name: '{name}'. "
            "Table names must start with a letter or underscore, "
            "and contain only letters, numbers, and underscores."
        )
    return name

TABLE_NAME = validate_table_name(config_loader.get_table_name())

# Logging will be set up in main() function
LOG_FILE = None


# ============================================================================
# MAIN SCRIPT
# ============================================================================

def get_username() -> str:
    """
    Get the current username (cross-platform).

    Returns:
        str: Username from environment variables (Windows: USERNAME, Unix: USER)
    """
    # Try Windows first, then Unix, then fallback
    import os
    return os.getenv('USERNAME') or os.getenv('USER') or 'YourUsername'


def get_dat_file_path(report_name: str) -> Path:
    """Construct the DAT file path based on username and report name from config"""
    username = get_username()
    return Path(DAT_FILE_PATTERN.format(username=username, report_name=report_name))


def create_database_name(report_name: str) -> str:
    """Generate database name based on report name"""
    return f"{report_name}.db"


def validate_report_name(report_name: str) -> bool:
    """
    Validate report name for invalid characters.

    Args:
        report_name: The report name to validate

    Returns:
        bool: True if valid, False otherwise
    """
    if not report_name:
        print("Error: report_name cannot be empty")
        return False

    # Check for path separators and other invalid characters
    invalid_chars = ['/', '\\', ':', '*', '?', '"', '<', '>', '|']
    for char in invalid_chars:
        if char in report_name:
            print(f"Error: report_name cannot contain '{char}' character")
            print(f"Invalid characters: {' '.join(invalid_chars)}")
            return False

    return True


def prompt_for_report_name() -> str:
    """Prompt user for report name, default to MyReport"""
    # Check if report name was passed as command-line argument
    if len(sys.argv) > 1:
        report_name = sys.argv[1].strip()
        if not validate_report_name(report_name):
            sys.exit(1)
        return report_name

    # Otherwise, prompt the user
    print("Enter report name (or press Enter for default 'MyReport'): ", end='')
    report_name = input().strip()

    if not report_name:
        report_name = DEFAULT_REPORT_NAME

    if not validate_report_name(report_name):
        sys.exit(1)

    return report_name


def create_table(cursor: sqlite3.Cursor) -> None:
    """Create the BBFCompass table with the official schema"""

    # Drop table if exists (for clean import)
    cursor.execute(f"DROP TABLE IF EXISTS {TABLE_NAME}")

    # Create table with official Babelfish Compass schema
    create_table_sql = f"""
    CREATE TABLE {TABLE_NAME} (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        babelfish_version VARCHAR(20) NOT NULL,
        date_imported TIMESTAMP NOT NULL,
        item VARCHAR(200) NOT NULL,
        itemDetail VARCHAR(200) NOT NULL,
        reportGroup VARCHAR(50) NOT NULL,
        status VARCHAR(20) NOT NULL,
        lineNr INT NOT NULL,
        appName VARCHAR(100) NOT NULL,
        srcFile VARCHAR(300) NOT NULL,
        batchNrinFile INT NOT NULL,
        batchLineInFile INT NOT NULL,
        context VARCHAR(200) NOT NULL,
        subcontext VARCHAR(200) NOT NULL,
        misc VARCHAR(20) NOT NULL,
        misc2 BIGINT NOT NULL,
        misc3 BIGINT NOT NULL
    )
    """

    cursor.execute(create_table_sql)
    logging.info(f"[OK] Table '{TABLE_NAME}' created successfully with official schema (16 columns)")


def import_dat_file(cursor: sqlite3.Cursor, dat_file_path: Path) -> int:
    """Import DAT file into SQLite table using batched inserts for better performance."""

    if not dat_file_path.exists():
        raise FileNotFoundError(f"DAT file not found: {dat_file_path}")

    logging.info(f"Reading DAT file: {dat_file_path}")

    # Column names matching the BBFCompass table schema (excluding id)
    columns = [
        'babelfish_version',
        'date_imported',
        'item',
        'itemDetail',
        'reportGroup',
        'status',
        'lineNr',
        'appName',
        'srcFile',
        'batchNrinFile',
        'batchLineInFile',
        'context',
        'subcontext',
        'misc',
        'misc2',
        'misc3'
    ]

    # Batch size for bulk inserts (improves performance significantly)
    BATCH_SIZE = 1000

    # Read the DAT file (semicolon-delimited, NO HEADER)
    with open(str(dat_file_path), 'r', encoding='utf-8') as f:
        # Use csv.reader with semicolon delimiter
        reader = csv.reader(f, delimiter=';')

        # Prepare insert statement with placeholders (16 columns)
        placeholders = ','.join(['?' for _ in range(16)])
        column_list = ','.join(columns)
        insert_sql = f"INSERT INTO {TABLE_NAME} ({column_list}) VALUES ({placeholders})"

        # Import rows in batches (no header to skip)
        row_count = 0
        batch = []

        for row in reader:
            if row and len(row) == 16:  # Ensure row has correct number of columns
                batch.append(row)

                # When batch is full, execute bulk insert
                if len(batch) >= BATCH_SIZE:
                    cursor.executemany(insert_sql, batch)
                    row_count += len(batch)
                    logging.info(f"  Imported {row_count} rows...")
                    batch = []  # Clear batch

            elif row:
                logging.warning(f"  Skipping row with {len(row)} columns (expected 16)")

        # Insert any remaining rows in the final batch
        if batch:
            cursor.executemany(insert_sql, batch)
            row_count += len(batch)
            logging.info(f"  Imported {row_count} rows...")

        logging.info(f"[OK] Successfully imported {row_count} rows using batched inserts")
        return row_count


def main() -> int:
    """Main execution function"""
    global LOG_FILE

    # Prompt for report name (checks command-line args first)
    report_name = prompt_for_report_name()

    # Setup logging after argument validation
    LOG_FILE = config_loader.setup_logging('03_Import_DAT_to_SQLite')

    # Get username
    username = get_username()

    # Log detailed information to file
    logging.info("=" * 80)
    logging.info("BABELFISH COMPASS DAT TO SQLITE IMPORTER")
    logging.info("=" * 80)
    logging.info(f"[OK] Current user: {username}")
    logging.info(f"[OK] Report name: {report_name}")
    logging.info(f"[OK] Log file: {LOG_FILE}")

    # Construct DAT file path
    dat_file_path = get_dat_file_path(report_name)
    logging.info(f"[OK] DAT file path: {dat_file_path}")

    # Verify DAT file exists before creating database
    if not dat_file_path.exists():
        logging.error(f"[ERROR] DAT file not found: {dat_file_path}")
        logging.error("-" * 80)
        logging.error("Please ensure:")
        logging.error("  1. Step 1 (Generate Report) was completed successfully")
        logging.error("  2. Step 2 (Generate DAT File) was completed successfully")
        logging.error("  3. The report name matches the name used in Steps 1 and 2")
        return 1

    # Create SQLite directory if it doesn't exist
    SQLITE_DIR.mkdir(parents=True, exist_ok=True)
    logging.info(f"[OK] SQLite directory: {SQLITE_DIR}")

    # Generate database name based on report name
    db_name = create_database_name(report_name)
    db_path = SQLITE_DIR / db_name
    logging.info(f"[OK] Database name: {db_name}")
    logging.info(f"[OK] Full path: {db_path}")

    try:
        # Connect to SQLite database (creates if doesn't exist)
        # Using context manager ensures connection is properly closed
        with sqlite3.connect(str(db_path)) as conn:
            cursor = conn.cursor()
            logging.info(f"[OK] Connected to SQLite database")

            # Create table with official BBFCompass schema
            create_table(cursor)

            # Import DAT file (no header in file)
            row_count = import_dat_file(cursor, dat_file_path)

            # Commit happens automatically on successful exit from context manager
            logging.info("[OK] Changes committed to database")

            # Display summary
            logging.info("=" * 80)
            logging.info("IMPORT SUMMARY")
            logging.info("=" * 80)
            logging.info(f"Database: {db_path}")
            logging.info(f"Table: {TABLE_NAME}")
            logging.info(f"Rows imported: {row_count}")

            # Query sample data
            cursor.execute(f"SELECT COUNT(*) FROM {TABLE_NAME}")
            total_rows = cursor.fetchone()[0]
            logging.info(f"Total rows in table: {total_rows}")

            logging.info("[OK] Import completed successfully!")
            logging.info("=" * 80)
            logging.info("")
            logging.info("NOTE: You may wish to delete the report files in:")
            # Use config pattern for cross-platform compatibility
            home_dir = Path.home()
            report_location = REPORT_LOCATION_PATTERN.format(home=home_dir, report_name=report_name)
            logging.info(f"      {report_location}")
            logging.info("      to free up disk space, as the data is now in SQLite.")
            logging.info("=" * 80)
            logging.info("")
            logging.info(f"Log file saved to: {LOG_FILE}")

        # Connection automatically closed here
        logging.info("[OK] Database connection closed")

    except FileNotFoundError as e:
        logging.error(f"[ERROR] {e}")
        logging.error("-" * 80)
        logging.error("Please check the report name and ensure the DAT file exists.")
        return 1

    except Exception as e:
        logging.error(f"[ERROR] {e}")
        logging.error("-" * 80)
        logging.error("Full traceback:")
        logging.error(traceback.format_exc())
        return 1

    return 0


if __name__ == "__main__":
    exit(main())

